### ISSUE TITLE
Log sampling

### ISSUE THREAD

**Issue by alexmuller** [Financial-Times/dotcom-reliability-kit#1197]
@andygout [mentioned this on Slack](https://financialtimes.slack.com/archives/C02B89GEQHF/p1726151466376789) (feel free to add more details if I missed anything Andy!)

## What problem does this feature solve?

Reduces log volume by sampling some high volume events, while allowing us to view general trends over time in Splunk.

## Ideal solution

?

## Alternatives

- Using a feature flag which we can enable/disable when we need to debug something specific.
- Metrics?

**Comment by rowanmanning** [comment]
I'm going to close this but it's not a "we will never implement this", we'd consider implementing if we get more requests for sampling at an application level and none of the following are possible for whatever reason.

These are in rough order of preference because the simpler / lowest code solution is nearly always best:

## Log levels

One way of avoiding certain logs from being a bit spammy is to set appropriate log levels and switch the `LOG_LEVEL` environment variable when you want to debug. E.g. if a log is only used for debugging then it should use `logger.debug()`. Your app would be configured with a `LOG_LEVEL` of `info` most of the time but then set to `debug` temporarily if you need more information.

## Ingest filtering

As most (all?) of our logs end up in Splunk, it's possible to define [Ingest Actions](https://lantern.splunk.com/Splunk_Platform/Product_Tips/Data_Management/Using_ingest_actions_in_Splunk_Enterprise) and sample logs that match a specific query. If log levels aren't appropriate then you could filter logs with specific events this way. @sjparkinson / EDO will be able to help with this.

## Wrapping your logging methods

If the above fail then you could adapt your own code to sample logs by wrapping calls. E.g.

```js
// 1 in 10 chance of being truthy
const doSampling = Math.floor(Math.random() * 10) === 1;

if (doSampling) {
    logger.info('You have a 1 in 10 chance of seeing me');
}
```

**Comment by sjparkinson** [comment]
> One way of avoiding certain logs from being a bit spammy is to set appropriate log levels and switch the `LOG_LEVEL` environment variable when you want to debug. E.g. if a log is only used for debugging then it should use `logger.debug()`.

To add to this, I fully agree with it as an approach, it feels well understood and would better help ensure each event sent has value.

We will eventually look to do more to publish some guidance on what a good info log looks like as part of proper logging governance project. But an initial thought is it's probably not something that is per-request, use debug for that by default, unless it's a change to data for example.
